export const AUTH_Z_MODULE_SERVICE = Symbol('AUTH_Z_MODULE_SERVICE');
export const AUTH_Z_CONTEXT_RESOLVER = Symbol('AUTH_Z_CONTEXT_RESOLVER');
export const AUTH_N_DECORATOR = Symbol('AUTH_N_DECORATOR');
export const AUTH_Z_DECORATOR = Symbol('AUTH_Z_DECORATOR');
export const AUTH_Z_REQUEST_CONTEXT = Symbol('AUTH_Z_REQUEST_CONTEXT');