export enum ErrorCategory {
  VALIDATION = 'VALIDATION',
  RESOURCE_NOT_FOUND = 'NOT_FOUND',
  AUTHENTICATION = 'AUTH_N',
  AUTHORIZATION = 'AUTH_Z',
  NETWORK = 'NETWORK',
  DATABASE = 'DATABASE',
  SYSTEM = 'SYSTEM',
  EXTERNAL_SERVICE = 'EXTERNAL_SERVICE',
}
